[build]
builder = "nixpacks"
buildCommand = "cd fs-frontend && npm install --force && npm run build && cd ../fs-backend && npm install"

[start]
startCommand = "cd fs-backend && npm run start & cd fs-frontend && ng serve --host 0.0.0.0 --port 4200"

[env]
NODE_VERSION = "18"
