[build]
builder = "nixpacks"
buildCommand = "cd fs-frontend && npm install --omit=dev --force && npm install -g @angular/cli --omit=dev --force && npm run build && cd ../fs-backend && npm install --omit=dev"

[env]
NODE_VERSION = "18"
